version: '3.8'

services:
  # 9. kiwi8
  kiwi8:
    build:
      context: /home/kdy987/work/kiwi8
      dockerfile: /home/kdy987/work/kiwi8/Dockerfile
    image: jskn_kiwi8_img
    container_name: jskn_kiwi8
    restart: always
    user: "1000:1000"
    ports:
      - "8003:8003"
    volumes:
      - /data/docker/apps/kiwi8:/app/data
    env_file:
      - /home/kdy987/work/kiwi8/.env.jskn
    environment:
      - TZ=Asia/Seoul
      - PYTHONPATH=/app
      - KIWI8_MODE=jskn
